version: '3.7'

services:
  web:
    build:
      context: ./up_site
      dockerfile: Dockerfile.prod
    command: gunicorn up_site.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/up_site/web/static
      - media_volume:/home/up_site/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/up_site/web/static
      - media_volume:/home/up_site/web/media
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  static_volume:
  media_volume:

