# Generated by Django 3.1 on 2020-08-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20200807_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_original',
        ),
    ]
