# Generated by Django 3.1 on 2020-08-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20200807_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='img_width',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_original',
            field=models.ImageField(height_field='img_height', upload_to='images/', width_field='img_width'),
        ),
    ]
