# Generated by Django 3.1 on 2020-08-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20200807_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(blank=True, default='image', max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
