# Generated by Django 3.1 on 2020-08-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_auto_20200808_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_original',
            field=models.ImageField(blank=True, height_field='img_height', upload_to='images/', verbose_name='Image', width_field='img_width'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Width'),
        ),
    ]
