# Generated by Django 3.1 on 2020-08-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20200809_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='last_height',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='LastHeight'),
        ),
        migrations.AddField(
            model_name='image',
            name='last_width',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='LastWidth'),
        ),
    ]
